#!/usr/bin/env bash
# Freebox Delta VM Debian 12 - Media stack installer / updater
# User model: one single VM user named "freebox".
#
# Fresh install:
#   - SSH port
#   - UFW firewall
#   - Apache + optional Let's Encrypt SSL
#   - Plex Media Server + Plex claim asked at the end
#   - rTorrent
#   - ruTorrent + plugins + dependencies
#
# Update mode:
#   - automatically detected
#   - lets you choose which actions to run
#
# Run:
#   sudo bash install_freebox_media_vm_final_v15.sh

set -Eeuo pipefail

export DEBIAN_FRONTEND=noninteractive

# -----------------------------
# Static choices
# -----------------------------
SCRIPT_VERSION="v15"

MAIN_USER="freebox"
MAIN_GROUP="freebox"

RUTORRENT_HTTP_USER="freebox"
RUTORRENT_DIR="/var/www/html/rutorrent"

RTORRENT_PEER_PORT="50000"
RTORRENT_SCGI_HOST="127.0.0.1"
RTORRENT_SCGI_PORT="5000"

STATE_DIR="/etc/freebox-media-installer"
STATE_FILE="${STATE_DIR}/state.conf"
LOG_FILE="/root/freebox-media-install.log"
CREDENTIALS_FILE="/root/freebox-media-credentials.txt"

PLEX_CLAIM_STATUS="non vérifié"
COMMAND="${1:-auto}"

# -----------------------------
# Colours
# -----------------------------
if command -v tput >/dev/null 2>&1; then
  GREEN="$(tput setaf 2 || true)"
  YELLOW="$(tput setaf 3 || true)"
  CYAN="$(tput setaf 6 || true)"
  RED="$(tput setaf 1 || true)"
  BOLD="$(tput bold || true)"
  RESET="$(tput sgr0 || true)"
else
  GREEN=""; YELLOW=""; CYAN=""; RED=""; BOLD=""; RESET=""
fi

log()  { echo -e "${CYAN}${1}${RESET}" | tee -a "$LOG_FILE"; }
ok()   { echo -e "${GREEN}${1}${RESET}" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}${1}${RESET}" | tee -a "$LOG_FILE"; }
fail() { echo -e "${RED}${1}${RESET}" | tee -a "$LOG_FILE"; }

prompt() {
  local text="$1"
  local default="$2"
  local reply=""
  read -rp "${YELLOW}${text} [${default}]${RESET}: " reply
  if [[ -z "$reply" ]]; then
    echo "$default"
  else
    echo "$reply"
  fi
}

ask_yes_no() {
  local text="$1"
  local default="${2:-yes}"
  local prompt_suffix="[y/N]"
  local reply=""

  if [[ "$default" == "yes" ]]; then
    prompt_suffix="[Y/n]"
  fi

  while true; do
    read -rp "${YELLOW}${text} ${prompt_suffix}${RESET}: " reply
    reply="${reply,,}"

    if [[ -z "$reply" ]]; then
      [[ "$default" == "yes" ]] && return 0 || return 1
    fi

    case "$reply" in
      y|yes|o|oui) return 0 ;;
      n|no|non) return 1 ;;
      *) warn "Réponse attendue : oui/non." ;;
    esac
  done
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    fail "Ce script doit être lancé en root : sudo bash $0"
    exit 1
  fi
}

backup_file_once() {
  local file="$1"
  if [[ -f "$file" && ! -f "${file}.freebox-bak" ]]; then
    cp -a "$file" "${file}.freebox-bak"
  fi
}

wait_for_port() {
  local host="$1"
  local port="$2"
  local timeout="${3:-30}"
  local i=0

  while (( i < timeout )); do
    if timeout 1 bash -c "cat < /dev/null > /dev/tcp/${host}/${port}" 2>/dev/null; then
      return 0
    fi
    sleep 1
    ((i++))
  done

  return 1
}

service_status_short() {
  local service="$1"
  if systemctl --quiet is-active "$service"; then
    echo "OK"
  else
    echo "KO"
  fi
}

detect_freebox_mounts() {
  # Detect all Freebox Delta disks mounted directly under /mnt.
  # Expected examples: /mnt/Freebox and /mnt/Freebox240.
  find /mnt -mindepth 1 -maxdepth 1 -type d -name 'Freebox*' 2>/dev/null | sort
}

repair_dpkg_if_needed() {
  # Previous failed installs can leave dpkg interrupted.
  # In that state apt refuses to install anything until dpkg --configure -a is run.
  if [[ -f /var/lib/dpkg/lock-frontend ]] || [[ -d /var/lib/dpkg/updates ]]; then
    log "Préparation APT/dpkg"
  fi

  if dpkg --audit 2>/dev/null | grep -q .; then
    warn "dpkg signale une installation interrompue. Correction automatique."
    dpkg --configure -a || {
      fail "Échec de dpkg --configure -a. Lance manuellement : sudo dpkg --configure -a"
      exit 1
    }
  fi

  apt-get -f install -y || {
    fail "Échec de apt-get -f install -y."
    fail "Lance manuellement : sudo dpkg --configure -a && sudo apt-get -f install"
    exit 1
  }
}

is_installed_legacy_or_current() {
  [[ -f "$STATE_FILE" ]] && return 0
  [[ -d "$RUTORRENT_DIR" ]] && return 0
  systemctl list-unit-files 2>/dev/null | grep -q '^rtorrent\.service' && return 0
  dpkg -s plexmediaserver >/dev/null 2>&1 && return 0
  return 1
}

load_state_defaults() {
  SAVED_SSH_PORT=""
  SAVED_MEDIA_ROOT=""
  SAVED_DOMAIN_NAME=""

  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE" || true
    SAVED_SSH_PORT="${SSH_PORT_SAVED:-}"
    SAVED_MEDIA_ROOT="${MEDIA_ROOT_SAVED:-}"
    SAVED_DOMAIN_NAME="${DOMAIN_NAME_SAVED:-}"
  fi
}

save_state() {
  mkdir -p "$STATE_DIR"

  cat > "$STATE_FILE" <<EOF
# Generated by install_freebox_media_vm_final_${SCRIPT_VERSION}.sh
INSTALLER_VERSION="${SCRIPT_VERSION}"
INSTALLED_AT="$(date -Is)"
SSH_PORT_SAVED="${SSH_PORT}"
MEDIA_ROOT_SAVED="${MEDIA_ROOT}"
DOMAIN_NAME_SAVED="${DOMAIN_NAME}"
RUTORRENT_DIR="${RUTORRENT_DIR}"
RTORRENT_PEER_PORT="${RTORRENT_PEER_PORT}"
RTORRENT_SCGI_PORT="${RTORRENT_SCGI_PORT}"
EOF

  chmod 600 "$STATE_FILE"
}

generate_rutorrent_password() {
  RUTORRENT_HTTP_PASS="$(openssl rand -hex 12)"
  ok "Mot de passe ruTorrent généré automatiquement."
}


load_existing_rutorrent_password_for_summary() {
  RUTORRENT_HTTP_PASS=""

  if [[ -f "$CREDENTIALS_FILE" ]]; then
    RUTORRENT_HTTP_PASS="$(awk -F ': ' '/ruTorrent mot de passe/ {print $2; exit}' "$CREDENTIALS_FILE" 2>/dev/null || true)"
  fi

  if [[ -z "$RUTORRENT_HTTP_PASS" ]]; then
    RUTORRENT_HTTP_PASS="inchangé / non connu"
  fi
}

reset_audit_recommendations() {
  AUDIT_ISSUES=0
  REC_PACKAGES="no"
  REC_SSH_FIREWALL="no"
  REC_DISKS_PERMS="no"
  REC_PLEX_INSTALL="no"
  REC_RTORRENT="no"
  REC_RUTORRENT_INSTALL="no"
  REC_RUTORRENT_PASSWORD="no"
  REC_APACHE="no"
  REC_SSL="no"
  REC_PLEX_CLAIM="no"
}

audit_ok() {
  local label="$1"
  local detail="${2:-}"
  ok "✓ ${label}${detail:+ - ${detail}}"
}

audit_warn() {
  local label="$1"
  local detail="${2:-}"
  warn "✗ ${label}${detail:+ - ${detail}}"
  AUDIT_ISSUES=$((AUDIT_ISSUES + 1))
}

configuration_audit() {
  reset_audit_recommendations

  echo
  log "Commande update : vérification de la configuration existante"

  # rTorrent
  RTORRENT_SERVICE_PRESENT="no"
  RTORRENT_SERVICE_ACTIVE="no"
  RTORRENT_PROCESS_PRESENT="no"

  if systemctl list-unit-files 2>/dev/null | grep -q '^rtorrent\.service'; then
    RTORRENT_SERVICE_PRESENT="yes"
  elif [[ -f /etc/systemd/system/rtorrent.service || -f /lib/systemd/system/rtorrent.service ]]; then
    RTORRENT_SERVICE_PRESENT="yes"
  fi

  if [[ "${RTORRENT_SERVICE_PRESENT}" == "yes" ]] && systemctl --quiet is-active rtorrent.service; then
    RTORRENT_SERVICE_ACTIVE="yes"
  fi

  if pgrep -u "${MAIN_USER}" -x rtorrent >/dev/null 2>&1 || pgrep -x rtorrent >/dev/null 2>&1; then
    RTORRENT_PROCESS_PRESENT="yes"
  fi

  if [[ "${RTORRENT_SERVICE_ACTIVE}" == "yes" ]]; then
    audit_ok "rTorrent service" "actif"
  elif [[ "${RTORRENT_PROCESS_PRESENT}" == "yes" ]]; then
    audit_ok "rTorrent process" "actif hors service systemd"
    warn "rTorrent fonctionne, mais rtorrent.service n'est pas actif. Aucune correction forcée tant que les ports répondent."
  elif [[ "${RTORRENT_SERVICE_PRESENT}" == "yes" ]]; then
    audit_warn "rTorrent service" "présent mais inactif"
    REC_RTORRENT="yes"
  else
    audit_warn "rTorrent service" "absent"
    REC_RTORRENT="yes"
  fi

  if [[ -f "/home/${MAIN_USER}/.rtorrent.rc" ]] \
    && grep -q "network.scgi.open_port = ${RTORRENT_SCGI_HOST}:${RTORRENT_SCGI_PORT}" "/home/${MAIN_USER}/.rtorrent.rc" \
    && grep -q "network.port_range.set = ${RTORRENT_PEER_PORT}-${RTORRENT_PEER_PORT}" "/home/${MAIN_USER}/.rtorrent.rc"; then
    audit_ok "Configuration rTorrent" ".rtorrent.rc cohérent"
  else
    audit_warn "Configuration rTorrent" ".rtorrent.rc absent ou incomplet"
    REC_RTORRENT="yes"
  fi

  # ruTorrent
  if [[ -d "${RUTORRENT_DIR}" ]]; then
    audit_ok "ruTorrent dossier" "${RUTORRENT_DIR}"
  else
    audit_warn "ruTorrent dossier" "absent"
    REC_PACKAGES="yes"
    REC_RUTORRENT_INSTALL="yes"
    REC_RUTORRENT_PASSWORD="yes"
    REC_APACHE="yes"
  fi

  if [[ -f "${RUTORRENT_DIR}/conf/config.local.php" ]] \
    && grep -q "\$scgi_host = \"${RTORRENT_SCGI_HOST}\"" "${RUTORRENT_DIR}/conf/config.local.php" \
    && grep -q "\$scgi_port = ${RTORRENT_SCGI_PORT}" "${RUTORRENT_DIR}/conf/config.local.php" \
    && grep -q "\$topDirectory = \"/mnt/\"" "${RUTORRENT_DIR}/conf/config.local.php"; then
    audit_ok "Configuration ruTorrent" "SCGI + topDirectory OK"
  else
    audit_warn "Configuration ruTorrent" "config.local.php absent ou non conforme"
    REC_RUTORRENT_INSTALL="yes"
    REC_APACHE="yes"
  fi

  if [[ -d "${RUTORRENT_DIR}/plugins" ]]; then
    AUDIT_PLUGIN_COUNT="$(find "${RUTORRENT_DIR}/plugins" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l || echo 0)"
    if [[ "${AUDIT_PLUGIN_COUNT}" -ge 10 ]]; then
      audit_ok "Plugins ruTorrent" "${AUDIT_PLUGIN_COUNT} dossiers"
    else
      audit_warn "Plugins ruTorrent" "${AUDIT_PLUGIN_COUNT} dossiers seulement"
      REC_RUTORRENT_INSTALL="yes"
      REC_APACHE="yes"
    fi
  else
    audit_warn "Plugins ruTorrent" "dossier plugins absent"
    REC_RUTORRENT_INSTALL="yes"
    REC_APACHE="yes"
  fi

  if [[ -f "${RUTORRENT_DIR}/.htpasswd" ]]; then
    audit_ok "Mot de passe ruTorrent" ".htpasswd présent"
  else
    audit_warn "Mot de passe ruTorrent" ".htpasswd absent"
    REC_RUTORRENT_PASSWORD="yes"
    REC_APACHE="yes"
  fi

  # Plex
  if dpkg -s plexmediaserver >/dev/null 2>&1; then
    if systemctl --quiet is-active plexmediaserver.service; then
      audit_ok "Plex Media Server" "installé et actif"
    else
      audit_warn "Plex Media Server" "installé mais inactif"
      REC_PLEX_INSTALL="yes"
    fi
  else
    audit_warn "Plex Media Server" "non installé"
    REC_PACKAGES="yes"
    REC_PLEX_INSTALL="yes"
  fi

  if wait_for_port 127.0.0.1 32400 3; then
    audit_ok "Port Plex local" "127.0.0.1:32400 répond"
  else
    audit_warn "Port Plex local" "127.0.0.1:32400 ne répond pas"
    REC_PLEX_INSTALL="yes"
  fi

  PLEX_PREFS="/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml"
  PLEX_IDENTITY="/tmp/plex-identity-audit.xml"
  if curl -sS "http://127.0.0.1:32400/identity" -o "${PLEX_IDENTITY}" 2>/dev/null \
    && grep -q 'claimed="1"' "${PLEX_IDENTITY}"; then
    audit_ok "Plex Claim" "déjà revendiqué"
  elif [[ -f "${PLEX_PREFS}" ]] && grep -Eq 'PlexOnlineToken="[^"]+"' "${PLEX_PREFS}"; then
    audit_ok "Plex Claim" "token présent dans Preferences.xml"
  else
    audit_warn "Plex Claim" "non revendiqué ou non vérifiable"
    REC_PLEX_CLAIM="yes"
  fi

  # Apache / homepage
  if systemctl --quiet is-active apache2.service; then
    audit_ok "Apache" "actif"
  else
    audit_warn "Apache" "inactif ou absent"
    REC_PACKAGES="yes"
    REC_APACHE="yes"
  fi

  if [[ -f /var/www/html/index.html ]] \
    && grep -q "Freebox Delta Media Server" /var/www/html/index.html \
    && grep -q "paypalme/FPLESSY565" /var/www/html/index.html \
    && grep -q "github.com/PFranck06/Freebox_Delta_VM_Plex_Rutorent" /var/www/html/index.html \
    && grep -q "/rutorrent" /var/www/html/index.html \
    && grep -q ":32400/web" /var/www/html/index.html; then
    audit_ok "Page d'accueil Apache" "Freebox Delta + Plex + ruTorrent + GitHub + PayPal"
  else
    audit_warn "Page d'accueil Apache" "absente ou non conforme"
    REC_APACHE="yes"
  fi

  if [[ -f /etc/apache2/sites-enabled/freebox-media.conf || -f /etc/apache2/sites-available/freebox-media.conf ]]; then
    audit_ok "VirtualHost Apache" "freebox-media présent"
  else
    audit_warn "VirtualHost Apache" "freebox-media absent"
    REC_APACHE="yes"
  fi

  # Ports
  if ss -ltn 2>/dev/null | grep -q ":80 "; then
    audit_ok "Port HTTP" "80 en écoute"
  else
    audit_warn "Port HTTP" "80 non détecté"
    REC_APACHE="yes"
  fi

  RTORRENT_SCGI_OK="no"
  RTORRENT_PEER_OK="no"

  if ss -ltn 2>/dev/null | grep -q ":${RTORRENT_SCGI_PORT} "; then
    RTORRENT_SCGI_OK="yes"
    audit_ok "Port SCGI rTorrent" "${RTORRENT_SCGI_PORT} en écoute"
  else
    audit_warn "Port SCGI rTorrent" "${RTORRENT_SCGI_PORT} non détecté"
    REC_RTORRENT="yes"
  fi

  if ss -ltn 2>/dev/null | grep -q ":${RTORRENT_PEER_PORT} "; then
    RTORRENT_PEER_OK="yes"
    audit_ok "Port peer rTorrent" "${RTORRENT_PEER_PORT} en écoute"
  else
    audit_warn "Port peer rTorrent" "${RTORRENT_PEER_PORT} non détecté"
    REC_RTORRENT="yes"
  fi

  if [[ "${RTORRENT_SCGI_OK}" == "yes" && "${RTORRENT_PEER_OK}" == "yes" ]] \
    && [[ -f "/home/${MAIN_USER}/.rtorrent.rc" ]] \
    && grep -q "network.scgi.open_port = ${RTORRENT_SCGI_HOST}:${RTORRENT_SCGI_PORT}" "/home/${MAIN_USER}/.rtorrent.rc" \
    && grep -q "network.port_range.set = ${RTORRENT_PEER_PORT}-${RTORRENT_PEER_PORT}" "/home/${MAIN_USER}/.rtorrent.rc"; then
    REC_RTORRENT="no"
  fi

  # Firewall
  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
    audit_ok "Firewall UFW" "actif"
  else
    audit_warn "Firewall UFW" "inactif ou absent"
    REC_SSH_FIREWALL="yes"
  fi

  for required_port in "${SAVED_SSH_PORT:-22222}" 80 443 32400 "${RTORRENT_PEER_PORT}"; do
    if ufw status 2>/dev/null | grep -q "${required_port}"; then
      audit_ok "Règle UFW ${required_port}" "présente"
    else
      audit_warn "Règle UFW ${required_port}" "absente ou non détectée"
      REC_SSH_FIREWALL="yes"
    fi
  done

  # Freebox disks
  if [[ ${#FREEBOX_MOUNTS[@]} -gt 0 ]]; then
    audit_ok "Disques Freebox détectés" "${FREEBOX_MOUNTS[*]}"
  else
    audit_warn "Disques Freebox détectés" "aucun /mnt/Freebox*"
    REC_DISKS_PERMS="yes"
  fi

  for FB_MOUNT in "${FREEBOX_MOUNTS[@]}"; do
    if [[ -d "${FB_MOUNT}" ]] && sudo -u "${MAIN_USER}" test -r "${FB_MOUNT}" && sudo -u "${MAIN_USER}" test -x "${FB_MOUNT}"; then
      audit_ok "Accès disque ${FB_MOUNT}" "${MAIN_USER} peut parcourir"
    else
      audit_warn "Accès disque ${FB_MOUNT}" "${MAIN_USER} ne peut pas parcourir"
      REC_DISKS_PERMS="yes"
    fi
  done

  # Dependencies between recommended actions.
  if [[ "$REC_RUTORRENT_INSTALL" == "yes" || "$REC_RUTORRENT_PASSWORD" == "yes" ]]; then
    REC_APACHE="yes"
  fi

  if [[ "$REC_RTORRENT" == "yes" || "$REC_RUTORRENT_INSTALL" == "yes" || "$REC_PLEX_INSTALL" == "yes" ]]; then
    REC_DISKS_PERMS="yes"
  fi

  if [[ "$REC_PLEX_INSTALL" == "yes" || "$REC_RTORRENT" == "yes" || "$REC_RUTORRENT_INSTALL" == "yes" ]]; then
    REC_PACKAGES="yes"
  fi

  echo
  if [[ "$AUDIT_ISSUES" -eq 0 ]]; then
    ok "Diagnostic terminé : aucune anomalie détectée."
  else
    warn "Diagnostic terminé : ${AUDIT_ISSUES} anomalie(s) détectée(s)."
    echo "Actions recommandées : packages=${REC_PACKAGES}, ssh/firewall=${REC_SSH_FIREWALL}, disks=${REC_DISKS_PERMS}, plex=${REC_PLEX_INSTALL}, rtorrent=${REC_RTORRENT}, rutorrent=${REC_RUTORRENT_INSTALL}, password=${REC_RUTORRENT_PASSWORD}, apache=${REC_APACHE}, ssl=${REC_SSL}, plex_claim=${REC_PLEX_CLAIM}"
  fi
}

apply_audit_recommendations() {
  DO_PACKAGES="$REC_PACKAGES"
  DO_SSH_FIREWALL="$REC_SSH_FIREWALL"
  DO_DISKS_PERMS="$REC_DISKS_PERMS"
  DO_PLEX_INSTALL="$REC_PLEX_INSTALL"
  DO_RTORRENT="$REC_RTORRENT"
  DO_RUTORRENT_INSTALL="$REC_RUTORRENT_INSTALL"
  DO_RUTORRENT_PASSWORD="$REC_RUTORRENT_PASSWORD"
  DO_APACHE="$REC_APACHE"
  DO_SSL="$REC_SSL"
  DO_PLEX_CLAIM="$REC_PLEX_CLAIM"
}


# -----------------------------
# Start
# -----------------------------
require_root
: > "$LOG_FILE"

echo
echo -e "${BOLD}${CYAN}Freebox Delta VM Debian 12 - installation média ${SCRIPT_VERSION}${RESET}"
echo -e "${CYAN}Modèle : utilisateur unique '${MAIN_USER}' pour la VM, rTorrent et les fichiers.${RESET}"
echo

load_state_defaults

if [[ "$COMMAND" == "update" || "$COMMAND" == "check" || "$COMMAND" == "audit" ]]; then
  INSTALL_MODE="update"
elif is_installed_legacy_or_current; then
  INSTALL_MODE="update"
else
  INSTALL_MODE="fresh"
fi

if [[ "$INSTALL_MODE" == "fresh" ]]; then
  log "Mode détecté : première installation complète"
else
  log "Mode détecté : installation existante / update"
fi

# Detect Freebox disks before questions.
mapfile -t FREEBOX_MOUNTS < <(detect_freebox_mounts)

if [[ ${#FREEBOX_MOUNTS[@]} -gt 0 ]]; then
  DEFAULT_MEDIA_ROOT="${FREEBOX_MOUNTS[0]}"
  if [[ -n "$SAVED_MEDIA_ROOT" ]]; then
    DEFAULT_MEDIA_ROOT="$SAVED_MEDIA_ROOT"
  elif [[ -d "/mnt/Freebox" ]]; then
    DEFAULT_MEDIA_ROOT="/mnt/Freebox"
  fi
  echo -e "${CYAN}Disques Freebox détectés : ${FREEBOX_MOUNTS[*]}${RESET}"
else
  DEFAULT_MEDIA_ROOT="${SAVED_MEDIA_ROOT:-/mnt/Freebox}"
  warn "Aucun disque /mnt/Freebox* détecté pour l'instant. Le script utilisera ${DEFAULT_MEDIA_ROOT} comme disque principal."
fi

# -----------------------------
# Action selection
# -----------------------------
DO_PACKAGES="no"
DO_SSH_FIREWALL="no"
DO_DISKS_PERMS="no"
DO_PLEX_INSTALL="no"
DO_RTORRENT="no"
DO_RUTORRENT_INSTALL="no"
DO_RUTORRENT_PASSWORD="no"
DO_APACHE="no"
DO_SSL="no"
DO_SSL_ASK="no"
DO_PLEX_CLAIM="no"

show_update_menu_and_select_actions() {
  echo
  echo -e "${BOLD}${CYAN}Actions disponibles pour l'update${RESET}"
  echo "1) Tout mettre à jour / reconfigurer"
  echo "2) Modifier uniquement le mot de passe ruTorrent"
  echo "3) Mettre à jour uniquement les droits/détection des disques Freebox"
  echo "4) Reconfigurer rTorrent + ruTorrent + Apache"
  echo "5) Mettre à jour Plex + vérifier/claim Plex"
  echo "6) Configurer/renouveler SSL domaine uniquement"
  echo "7) Choix personnalisé"
  echo

  UPDATE_CHOICE="$(prompt "Choix update" "2")"

  case "$UPDATE_CHOICE" in
    1)
      DO_PACKAGES="yes"
      DO_SSH_FIREWALL="yes"
      DO_DISKS_PERMS="yes"
      DO_PLEX_INSTALL="yes"
      DO_RTORRENT="yes"
      DO_RUTORRENT_INSTALL="yes"
      DO_RUTORRENT_PASSWORD="yes"
      DO_APACHE="yes"
      DO_SSL_ASK="yes"
      DO_PLEX_CLAIM="yes"
      ;;
    2)
      DO_RUTORRENT_PASSWORD="yes"
      DO_APACHE="yes"
      ;;
    3)
      DO_DISKS_PERMS="yes"
      ;;
    4)
      DO_PACKAGES="yes"
      DO_DISKS_PERMS="yes"
      DO_RTORRENT="yes"
      DO_RUTORRENT_INSTALL="yes"
      DO_RUTORRENT_PASSWORD="yes"
      DO_APACHE="yes"
      ;;
    5)
      DO_PACKAGES="yes"
      DO_PLEX_INSTALL="yes"
      DO_PLEX_CLAIM="yes"
      DO_DISKS_PERMS="yes"
      ;;
    6)
      DO_PACKAGES="yes"
      DO_APACHE="yes"
      DO_SSL="yes"
      ;;
    7)
      ask_yes_no "Installer / mettre à jour les paquets ?" "yes" && DO_PACKAGES="yes"
      ask_yes_no "Reconfigurer SSH + firewall ?" "no" && DO_SSH_FIREWALL="yes"
      ask_yes_no "Redétecter les disques Freebox + droits ?" "yes" && DO_DISKS_PERMS="yes"
      ask_yes_no "Installer / mettre à jour Plex ?" "no" && DO_PLEX_INSTALL="yes"
      ask_yes_no "Reconfigurer rTorrent ?" "no" && DO_RTORRENT="yes"
      ask_yes_no "Réinstaller proprement ruTorrent ?" "no" && DO_RUTORRENT_INSTALL="yes"
      ask_yes_no "Régénérer le mot de passe ruTorrent ?" "yes" && DO_RUTORRENT_PASSWORD="yes"
      ask_yes_no "Reconfigurer Apache ?" "no" && DO_APACHE="yes"
      ask_yes_no "Configurer SSL domaine ?" "no" && DO_SSL="yes"
      ask_yes_no "Vérifier / claim Plex ?" "no" && DO_PLEX_CLAIM="yes"
      ;;
    *)
      warn "Choix inconnu : mode sécurité, mot de passe ruTorrent uniquement."
      DO_RUTORRENT_PASSWORD="yes"
      DO_APACHE="yes"
      ;;
  esac
}

if [[ "$INSTALL_MODE" == "fresh" ]]; then
  DO_PACKAGES="yes"
  DO_SSH_FIREWALL="yes"
  DO_DISKS_PERMS="yes"
  DO_PLEX_INSTALL="yes"
  DO_RTORRENT="yes"
  DO_RUTORRENT_INSTALL="yes"
  DO_RUTORRENT_PASSWORD="yes"
  DO_APACHE="yes"
  DO_SSL_ASK="yes"
  DO_PLEX_CLAIM="yes"
else
  if [[ "$COMMAND" == "update" || "$COMMAND" == "check" || "$COMMAND" == "audit" ]]; then
    configuration_audit

    if [[ "$COMMAND" == "check" || "$COMMAND" == "audit" ]]; then
      if [[ "$AUDIT_ISSUES" -eq 0 ]]; then
        ok "Commande ${COMMAND} : diagnostic seul, aucune action à appliquer."
      else
        warn "Commande ${COMMAND} : diagnostic seul. Relance avec 'update' pour appliquer les corrections."
      fi
    elif [[ "$AUDIT_ISSUES" -eq 0 ]]; then
      if ask_yes_no "Aucune anomalie détectée. Ouvrir quand même le menu update ?" "no"; then
        show_update_menu_and_select_actions
      else
        ok "Aucune action sélectionnée."
      fi
    else
      echo
      echo -e "${BOLD}${CYAN}Mise à jour proposée après diagnostic${RESET}"
      echo "1) Appliquer les corrections recommandées"
      echo "2) Ouvrir le menu update classique"
      echo "3) Diagnostic seulement, ne rien modifier"
      echo

      AUDIT_CHOICE="$(prompt "Choix" "1")"

      case "$AUDIT_CHOICE" in
        1)
          apply_audit_recommendations
          ;;
        2)
          show_update_menu_and_select_actions
          ;;
        3)
          ok "Diagnostic seulement : aucune modification appliquée."
          ;;
        *)
          warn "Choix inconnu : aucune modification appliquée."
          ;;
      esac
    fi
  else
    show_update_menu_and_select_actions
  fi
fi

# Apache is required when installing ruTorrent or changing its HTTP password.
if [[ "$DO_RUTORRENT_INSTALL" == "yes" || "$DO_RUTORRENT_PASSWORD" == "yes" ]]; then
  DO_APACHE="yes"
fi

# Disk permissions are required for rTorrent/ruTorrent/Plex access.
if [[ "$DO_RTORRENT" == "yes" || "$DO_RUTORRENT_INSTALL" == "yes" || "$DO_PLEX_INSTALL" == "yes" ]]; then
  DO_DISKS_PERMS="yes"
fi

# -----------------------------
# Questions
# -----------------------------
log "Questions initiales"

DEFAULT_SSH_PORT="${SAVED_SSH_PORT:-2212}"
if [[ "$DO_SSH_FIREWALL" == "yes" ]]; then
  SSH_PORT="$(prompt "Port SSH souhaité" "$DEFAULT_SSH_PORT")"
else
  SSH_PORT="$DEFAULT_SSH_PORT"
fi

if [[ "$DO_DISKS_PERMS" == "yes" || "$DO_RTORRENT" == "yes" || "$DO_RUTORRENT_INSTALL" == "yes" || "$DO_PLEX_INSTALL" == "yes" ]]; then
  MEDIA_ROOT="$(prompt "Disque principal pour les téléchargements rTorrent" "$DEFAULT_MEDIA_ROOT")"
else
  MEDIA_ROOT="$DEFAULT_MEDIA_ROOT"
fi

# Ensure selected main disk is in the disk list.
if [[ ${#FREEBOX_MOUNTS[@]} -eq 0 ]]; then
  FREEBOX_MOUNTS=("${MEDIA_ROOT}")
else
  FOUND_MEDIA_ROOT="no"
  for m in "${FREEBOX_MOUNTS[@]}"; do
    if [[ "$m" == "$MEDIA_ROOT" ]]; then
      FOUND_MEDIA_ROOT="yes"
      break
    fi
  done
  if [[ "$FOUND_MEDIA_ROOT" != "yes" ]]; then
    FREEBOX_MOUNTS+=("${MEDIA_ROOT}")
  fi
fi

FREEBOX_MOUNTS_TEXT="$(printf '%s ' "${FREEBOX_MOUNTS[@]}")"
FREEBOX_MOUNTS_DISPLAY="$(printf '%s, ' "${FREEBOX_MOUNTS[@]}")"
FREEBOX_MOUNTS_DISPLAY="${FREEBOX_MOUNTS_DISPLAY%, }"

DEFAULT_DOMAIN_NAME="${SAVED_DOMAIN_NAME:-}"
DOMAIN_NAME="$DEFAULT_DOMAIN_NAME"
LETSENCRYPT_EMAIL=""

# Fresh install and "full update" must ask the previous SSL/domain question at the start.
# If a domain is supplied, SSL is enabled; if left empty, SSL is skipped.
if [[ "$DO_SSL_ASK" == "yes" || "$DO_SSL" == "yes" ]]; then
  DOMAIN_NAME="$(prompt "Nom de domaine pour Apache/SSL, vide = pas de SSL" "$DEFAULT_DOMAIN_NAME")"
  if [[ -n "$DOMAIN_NAME" ]]; then
    DO_SSL="yes"
    LETSENCRYPT_EMAIL="$(prompt "Email Let's Encrypt" "admin@${DOMAIN_NAME}")"
  else
    warn "Aucun domaine fourni : SSL ignoré."
    DO_SSL="no"
  fi
elif [[ "$DO_APACHE" == "yes" && -n "$DEFAULT_DOMAIN_NAME" ]]; then
  DOMAIN_NAME="$DEFAULT_DOMAIN_NAME"
fi

# Plex Claim Token expires quickly, so it is asked at the end if needed.
PLEX_CLAIM_TOKEN=""

TOR_BASE="${MEDIA_ROOT}/Torrents"
WATCH_DIR="${TOR_BASE}/watch"
DOWNLOAD_DIR="${TOR_BASE}/downloads"
SESSION_DIR="${TOR_BASE}/session"

if [[ "$DO_RUTORRENT_PASSWORD" == "yes" ]]; then
  RUTORRENT_HTTP_PASS=""
else
  load_existing_rutorrent_password_for_summary
fi

echo
log "Paramètres retenus"
echo "Mode                            : ${INSTALL_MODE}"
echo "Utilisateur système             : ${MAIN_USER}"
echo "Port SSH                        : ${SSH_PORT}"
echo "Disque principal rTorrent       : ${MEDIA_ROOT}"
echo "Tous les disques Freebox        : ${FREEBOX_MOUNTS_DISPLAY}"
echo "Dossier torrents                : ${TOR_BASE}"
echo "Port rTorrent peer              : ${RTORRENT_PEER_PORT}"
echo "SCGI rTorrent                   : ${RTORRENT_SCGI_HOST}:${RTORRENT_SCGI_PORT}"
echo "Utilisateur HTTP ruTorrent      : ${RUTORRENT_HTTP_USER}"
if [[ "$DO_RUTORRENT_PASSWORD" == "yes" ]]; then
  echo "Mot de passe ruTorrent          : sera généré automatiquement"
else
  echo "Mot de passe ruTorrent          : inchangé"
fi
if [[ -n "$DOMAIN_NAME" ]]; then
  echo "Nom de domaine                  : ${DOMAIN_NAME}"
else
  echo "SSL                             : ignoré"
fi
echo "Actions                         : packages=${DO_PACKAGES}, ssh/firewall=${DO_SSH_FIREWALL}, disks=${DO_DISKS_PERMS}, plex=${DO_PLEX_INSTALL}, rtorrent=${DO_RTORRENT}, rutorrent=${DO_RUTORRENT_INSTALL}, password=${DO_RUTORRENT_PASSWORD}, apache=${DO_APACHE}, ssl=${DO_SSL}, plex_claim=${DO_PLEX_CLAIM}"
echo

# -----------------------------
# 2) Install packages
# -----------------------------
if [[ "$DO_PACKAGES" == "yes" ]]; then
  log "Installation / mise à jour des paquets"

  repair_dpkg_if_needed
  apt-get update -y

  if id "${MAIN_USER}" >/dev/null 2>&1; then
    ok "Utilisateur ${MAIN_USER} existant."
  else
    warn "Utilisateur ${MAIN_USER} absent : création."
    adduser --disabled-password --gecos "" "${MAIN_USER}"
  fi

  if ! getent group "${MAIN_GROUP}" >/dev/null 2>&1; then
    groupadd "${MAIN_GROUP}"
  fi

  usermod -aG sudo "${MAIN_USER}" || true
  usermod -aG "${MAIN_GROUP}" "${MAIN_USER}" || true

  CORE_PACKAGES=(
    sudo
    curl
    ca-certificates
    gnupg2
    lsb-release
    apt-transport-https
    git
    ufw
    apache2
    apache2-utils
    php
    php-cli
    php-cgi
    php-fpm
    php-mbstring
    php-xml
    php-curl
    php-gd
    php-zip
    php-intl
    php-bcmath
    rtorrent
    ffmpeg
    mediainfo
    sox
    unzip
    p7zip-full
    unar
    unrar-free
    python3
    python3-pip
    sqlite3
    xmlrpc-api-utils
    acl
    ssl-cert
    openssl
  )

  if [[ "$DO_SSL" == "yes" ]]; then
    CORE_PACKAGES+=(certbot python3-certbot-apache)
  fi

  apt-get install -y "${CORE_PACKAGES[@]}"

  if apt-cache show dumptorrent >/dev/null 2>&1; then
    apt-get install -y dumptorrent || warn "dumptorrent détecté mais installation échouée."
  else
    warn "dumptorrent indisponible dans les dépôts : le plugin ruTorrent 'dump' sera désactivé si présent."
  fi

  if [[ "$DO_PLEX_INSTALL" == "yes" ]]; then
    log "Installation / mise à jour Plex Media Server"
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://downloads.plex.tv/plex-keys/PlexSign.v2.key \
      | gpg --dearmor --yes -o /etc/apt/keyrings/plexmediaserver.v2.gpg
    chmod 0644 /etc/apt/keyrings/plexmediaserver.v2.gpg

    cat > /etc/apt/sources.list.d/plex.list <<'PLEXREPO'
deb [signed-by=/etc/apt/keyrings/plexmediaserver.v2.gpg] https://repo.plex.tv/deb/ public main
PLEXREPO

    apt-get update -y
    apt-get install -y plexmediaserver
  fi
else
  # Minimal packages required for selected update actions.
  NEED_MIN_PKGS=()
  if [[ "$DO_RUTORRENT_PASSWORD" == "yes" ]]; then
    command -v htpasswd >/dev/null 2>&1 || NEED_MIN_PKGS+=(apache2-utils)
    command -v openssl >/dev/null 2>&1 || NEED_MIN_PKGS+=(openssl)
  fi
  if [[ "$DO_DISKS_PERMS" == "yes" ]]; then
    command -v setfacl >/dev/null 2>&1 || NEED_MIN_PKGS+=(acl)
  fi
  if [[ "$DO_SSL" == "yes" ]]; then
    command -v certbot >/dev/null 2>&1 || NEED_MIN_PKGS+=(certbot python3-certbot-apache)
  fi
  if [[ ${#NEED_MIN_PKGS[@]} -gt 0 ]]; then
    log "Installation minimale requise pour les actions choisies : ${NEED_MIN_PKGS[*]}"
    repair_dpkg_if_needed
    apt-get update -y
    apt-get install -y "${NEED_MIN_PKGS[@]}"
  fi
fi

# User/group must exist even in minimal update.
if ! id "${MAIN_USER}" >/dev/null 2>&1; then
  adduser --disabled-password --gecos "" "${MAIN_USER}"
fi
if ! getent group "${MAIN_GROUP}" >/dev/null 2>&1; then
  groupadd "${MAIN_GROUP}"
fi
usermod -aG sudo "${MAIN_USER}" || true
usermod -aG "${MAIN_GROUP}" "${MAIN_USER}" || true

# External binaries compatibility for ruTorrent plugins.
if command -v python3 >/dev/null 2>&1 && ! command -v python >/dev/null 2>&1; then
  ln -sf /usr/bin/python3 /usr/local/bin/python
fi

if ! command -v unrar >/dev/null 2>&1; then
  if command -v unrar-free >/dev/null 2>&1; then
    ln -sf "$(command -v unrar-free)" /usr/local/bin/unrar
  elif command -v unar >/dev/null 2>&1; then
    ln -sf "$(command -v unar)" /usr/local/bin/unrar
  fi
fi

if [[ "$DO_RUTORRENT_PASSWORD" == "yes" ]]; then
  generate_rutorrent_password
fi

# -----------------------------
# 3) Configuration
# -----------------------------

if [[ "$DO_SSH_FIREWALL" == "yes" ]]; then
  log "Configuration SSH"
  SSHD_CONFIG="/etc/ssh/sshd_config"
  backup_file_once "$SSHD_CONFIG"

  if grep -qE '^[#[:space:]]*Port[[:space:]]+' "$SSHD_CONFIG"; then
    sed -i "s/^[#[:space:]]*Port[[:space:]].*/Port ${SSH_PORT}/" "$SSHD_CONFIG"
  else
    echo "Port ${SSH_PORT}" >> "$SSHD_CONFIG"
  fi

  if grep -qE '^[#[:space:]]*PermitRootLogin[[:space:]]+' "$SSHD_CONFIG"; then
    sed -i 's/^[#[:space:]]*PermitRootLogin[[:space:]].*/PermitRootLogin no/' "$SSHD_CONFIG"
  else
    echo "PermitRootLogin no" >> "$SSHD_CONFIG"
  fi

  if grep -qE '^[#[:space:]]*PasswordAuthentication[[:space:]]+' "$SSHD_CONFIG"; then
    sed -i 's/^[#[:space:]]*PasswordAuthentication[[:space:]].*/PasswordAuthentication yes/' "$SSHD_CONFIG"
  else
    echo "PasswordAuthentication yes" >> "$SSHD_CONFIG"
  fi

  systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || warn "SSH non redémarré automatiquement."

  log "Configuration UFW"
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow "${SSH_PORT}/tcp" comment "SSH"
  ufw allow 80/tcp comment "Apache HTTP"
  ufw allow 443/tcp comment "Apache HTTPS"
  ufw allow 32400/tcp comment "Plex"
  ufw allow "${RTORRENT_PEER_PORT}/tcp" comment "rTorrent peer"
  ufw --force enable
fi

if [[ "$DO_APACHE" == "yes" || "$DO_SSL" == "yes" ]]; then
  log "Activation modules Apache"
  a2enmod proxy proxy_http proxy_scgi rewrite headers ssl auth_basic authn_file >/dev/null || true
fi

if [[ "$DO_DISKS_PERMS" == "yes" ]]; then
  log "Configuration des droits et dossiers"

  if [[ ! -d "${MEDIA_ROOT}" ]]; then
    warn "Le disque principal ${MEDIA_ROOT} n'existe pas. Création locale, mais vérifie le montage CIFS."
    mkdir -p "${MEDIA_ROOT}"
  fi

  mkdir -p "${WATCH_DIR}" "${DOWNLOAD_DIR}" "${SESSION_DIR}"

  usermod -aG "${MAIN_GROUP}" www-data || true
  usermod -aG "${MAIN_GROUP}" plex || true

  # Give access to every detected Freebox disk mounted under /mnt/Freebox*.
  # We do not recursively chmod/chgrp full disks to avoid breaking large disks or special folders.
  # rTorrent runs as "freebox", so CIFS mounts using uid=freebox,gid=freebox are enough for write access.
  for FB_MOUNT in "${FREEBOX_MOUNTS[@]}"; do
    if [[ -d "${FB_MOUNT}" ]]; then
      setfacl -m "u:${MAIN_USER}:rwx,u:www-data:rx,u:plex:rx,g:${MAIN_GROUP}:rwx" "${FB_MOUNT}" 2>/dev/null || true
      setfacl -d -m "u:${MAIN_USER}:rwx,u:www-data:rx,u:plex:rx,g:${MAIN_GROUP}:rwx" "${FB_MOUNT}" 2>/dev/null || true

      if sudo -u "${MAIN_USER}" test -r "${FB_MOUNT}" && sudo -u "${MAIN_USER}" test -x "${FB_MOUNT}"; then
        ok "rTorrent/freebox peut parcourir ${FB_MOUNT}."
      else
        warn "rTorrent/freebox ne peut pas parcourir ${FB_MOUNT}. Vérifie le montage CIFS."
      fi

      if id plex >/dev/null 2>&1 && sudo -u plex test -r "${FB_MOUNT}" && sudo -u plex test -x "${FB_MOUNT}"; then
        ok "Plex peut parcourir ${FB_MOUNT}."
      else
        warn "Plex ne peut pas parcourir ${FB_MOUNT}. Vérifie le montage CIFS : uid=freebox,gid=freebox,dir_mode=0775,file_mode=0664."
      fi
    else
      warn "Disque Freebox détecté/choisi absent : ${FB_MOUNT}"
    fi
  done

  # Manage the application subtree recursively because rTorrent and ruTorrent must write there.
  chown -R "${MAIN_USER}:${MAIN_GROUP}" "${TOR_BASE}" 2>/dev/null || true
  chmod -R 775 "${TOR_BASE}" 2>/dev/null || true
  setfacl -R -m "u:${MAIN_USER}:rwx,u:www-data:rwx,u:plex:rx,g:${MAIN_GROUP}:rwx" "${TOR_BASE}" 2>/dev/null || true
  setfacl -dR -m "u:${MAIN_USER}:rwx,u:www-data:rwx,u:plex:rx,g:${MAIN_GROUP}:rwx" "${TOR_BASE}" 2>/dev/null || true
fi

if [[ "$DO_PLEX_INSTALL" == "yes" ]]; then
  log "Activation Plex Media Server"
  usermod -aG "${MAIN_GROUP}" plex || true
  systemctl enable --now plexmediaserver
  systemctl restart plexmediaserver
fi

if [[ "$DO_RTORRENT" == "yes" ]]; then
  log "Configuration rTorrent"

  systemctl stop rtorrent.service 2>/dev/null || true
  pkill -u "${MAIN_USER}" rtorrent 2>/dev/null || true
  rm -f "${SESSION_DIR}/rtorrent.lock" 2>/dev/null || true

  cat > "/home/${MAIN_USER}/.rtorrent.rc" <<EOF
# Generated by install_freebox_media_vm_final_${SCRIPT_VERSION}.sh

directory.default.set = ${DOWNLOAD_DIR}
session.path.set = ${SESSION_DIR}

network.port_range.set = ${RTORRENT_PEER_PORT}-${RTORRENT_PEER_PORT}
network.port_random.set = no

network.scgi.open_port = ${RTORRENT_SCGI_HOST}:${RTORRENT_SCGI_PORT}

throttle.global_down.max_rate.set_kb = 0
throttle.global_up.max_rate.set_kb = 0
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# Better compatibility for public torrents.
dht.mode.set = auto
protocol.pex.set = yes

# Optional watch folder:
# schedule = watch_directory,5,5,"load.start=${WATCH_DIR}/*.torrent"
EOF

  chown "${MAIN_USER}:${MAIN_GROUP}" "/home/${MAIN_USER}/.rtorrent.rc"
  chmod 640 "/home/${MAIN_USER}/.rtorrent.rc"

  cat > /etc/systemd/system/rtorrent.service <<EOF
[Unit]
Description=rTorrent daemon for ${MAIN_USER}
After=network-online.target
Wants=network-online.target
RequiresMountsFor=${FREEBOX_MOUNTS_TEXT}

[Service]
Type=simple
User=${MAIN_USER}
Group=${MAIN_GROUP}
UMask=002
WorkingDirectory=/home/${MAIN_USER}
ExecStartPre=-/usr/bin/rm -f ${SESSION_DIR}/rtorrent.lock
ExecStart=/usr/bin/rtorrent -n -o import=/home/${MAIN_USER}/.rtorrent.rc -o system.daemon.set=true
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now rtorrent.service
fi

if [[ "$DO_RUTORRENT_INSTALL" == "yes" ]]; then
  log "Installation propre de ruTorrent"

  if [[ -d "${RUTORRENT_DIR}" ]]; then
    TS="$(date +%Y%m%d-%H%M%S)"
    mv "${RUTORRENT_DIR}" "${RUTORRENT_DIR}.bak-${TS}"
    ok "Ancien ruTorrent sauvegardé : ${RUTORRENT_DIR}.bak-${TS}"
  fi

  git clone --recursive https://github.com/Novik/ruTorrent.git "${RUTORRENT_DIR}"
  git config --global --add safe.directory "${RUTORRENT_DIR}" || true
  git -C "${RUTORRENT_DIR}" submodule update --init --recursive || true

  cat > "${RUTORRENT_DIR}/conf/config.local.php" <<EOF
<?php
// Generated by install_freebox_media_vm_final_${SCRIPT_VERSION}.sh
\$scgi_host = "${RTORRENT_SCGI_HOST}";
\$scgi_port = ${RTORRENT_SCGI_PORT};
\$XMLRPCMountPoint = "/RPC2";
\$topDirectory = "/mnt/";
\$log_file = "/tmp/rutorrent-errors.log";
\$do_diagnostic = true;
\$al_diagnostic = true;

\$pathToExternals["php"] = "/usr/bin/php";
\$pathToExternals["curl"] = "/usr/bin/curl";
\$pathToExternals["python"] = "/usr/local/bin/python";
\$pathToExternals["sox"] = "/usr/bin/sox";
\$pathToExternals["unzip"] = "/usr/bin/unzip";
\$pathToExternals["unrar"] = "/usr/local/bin/unrar";
\$pathToExternals["ffmpeg"] = "/usr/bin/ffmpeg";
\$pathToExternals["mediainfo"] = "/usr/bin/mediainfo";
if (file_exists("/usr/bin/dumptorrent")) {
    \$pathToExternals["dumptorrent"] = "/usr/bin/dumptorrent";
}
EOF

  if [[ ! -f "${RUTORRENT_DIR}/conf/plugins.ini" ]]; then
    cat > "${RUTORRENT_DIR}/conf/plugins.ini" <<'EOF'
[default]
enabled = user-defined
canChangeToolbar = yes
canChangeMenu = yes
canChangeOptions = yes
canChangeTabs = yes
canChangeColumns = yes
canChangeStatusBar = yes
canChangeCategory = yes
canBeShutdowned = yes
EOF
  fi

  if ! command -v dumptorrent >/dev/null 2>&1 && [[ -d "${RUTORRENT_DIR}/plugins/dump" ]]; then
    mv "${RUTORRENT_DIR}/plugins/dump" "${RUTORRENT_DIR}/plugins/dump.disabled"
    warn "Plugin dump désactivé : dumptorrent absent."
  fi

  chown -R www-data:"${MAIN_GROUP}" "${RUTORRENT_DIR}"
  chmod -R 775 "${RUTORRENT_DIR}"
  setfacl -R -m "u:www-data:rwx,u:${MAIN_USER}:rwx,g:${MAIN_GROUP}:rwx" "${RUTORRENT_DIR}" 2>/dev/null || true
  setfacl -dR -m "u:www-data:rwx,u:${MAIN_USER}:rwx,g:${MAIN_GROUP}:rwx" "${RUTORRENT_DIR}" 2>/dev/null || true
fi

if [[ -d "${RUTORRENT_DIR}/plugins" ]]; then
  PLUGIN_COUNT="$(find "${RUTORRENT_DIR}/plugins" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l || echo 0)"
else
  PLUGIN_COUNT="0"
fi

if [[ "$DO_RUTORRENT_PASSWORD" == "yes" ]]; then
  log "Configuration du mot de passe ruTorrent"

  if [[ ! -d "${RUTORRENT_DIR}" ]]; then
    fail "ruTorrent n'est pas installé dans ${RUTORRENT_DIR}. Impossible de créer le mot de passe."
    exit 1
  fi

  htpasswd -Bbc "${RUTORRENT_DIR}/.htpasswd" "${RUTORRENT_HTTP_USER}" "${RUTORRENT_HTTP_PASS}"
  chown root:www-data "${RUTORRENT_DIR}/.htpasswd"
  chmod 640 "${RUTORRENT_DIR}/.htpasswd"

  if htpasswd -vb "${RUTORRENT_DIR}/.htpasswd" "${RUTORRENT_HTTP_USER}" "${RUTORRENT_HTTP_PASS}" >/dev/null 2>&1; then
    ok "Mot de passe ruTorrent validé pour l'utilisateur HTTP '${RUTORRENT_HTTP_USER}'."
  else
    fail "La validation htpasswd a échoué pour ruTorrent."
    exit 1
  fi

  cat > "$CREDENTIALS_FILE" <<EOF
ruTorrent URL local : http://<IP_VM>/rutorrent
ruTorrent utilisateur : ${RUTORRENT_HTTP_USER}
ruTorrent mot de passe : ${RUTORRENT_HTTP_PASS}
EOF
  chmod 600 "$CREDENTIALS_FILE"
fi

if [[ "$DO_APACHE" == "yes" ]]; then
  log "Configuration Apache vhost"

  if [[ "$DO_RUTORRENT_PASSWORD" != "yes" && ! -f "${RUTORRENT_DIR}/.htpasswd" ]]; then
    warn "Aucun .htpasswd existant. Génération d'un mot de passe ruTorrent pour protéger l'accès."
    generate_rutorrent_password
    DO_RUTORRENT_PASSWORD="yes"
    htpasswd -Bbc "${RUTORRENT_DIR}/.htpasswd" "${RUTORRENT_HTTP_USER}" "${RUTORRENT_HTTP_PASS}"
    chown root:www-data "${RUTORRENT_DIR}/.htpasswd"
    chmod 640 "${RUTORRENT_DIR}/.htpasswd"
  fi

  SERVERNAME_LINE=""
  if [[ -n "${DOMAIN_NAME}" ]]; then
    SERVERNAME_LINE="ServerName ${DOMAIN_NAME}"
  fi

  log "Création de la page d'accueil Apache Freebox Delta"

  cat > /var/www/html/index.html <<'EOF'
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Freebox Delta Media Server</title>
  <meta name="robots" content="noindex,nofollow">
  <style>
    :root {
      --bg1: #111827;
      --bg2: #0f172a;
      --card: rgba(255,255,255,.09);
      --card-border: rgba(255,255,255,.18);
      --text: #f8fafc;
      --muted: #cbd5e1;
      --accent: #00a8ff;
      --plex: #e5a00d;
      --rutorrent: #4ade80;
      --paypal: #0070ba;
      --github: #24292f;
      --shadow: 0 20px 60px rgba(0,0,0,.35);
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      min-height: 100vh;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--text);
      background:
        radial-gradient(circle at top left, rgba(0,168,255,.28), transparent 36rem),
        radial-gradient(circle at bottom right, rgba(229,160,13,.18), transparent 34rem),
        linear-gradient(135deg, var(--bg1), var(--bg2));
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 2rem;
    }

    main {
      width: min(980px, 100%);
    }

    .hero {
      text-align: center;
      margin-bottom: 2rem;
    }

    .badge {
      display: inline-flex;
      align-items: center;
      gap: .5rem;
      padding: .45rem .8rem;
      border: 1px solid var(--card-border);
      border-radius: 999px;
      background: rgba(255,255,255,.08);
      color: var(--muted);
      font-size: .9rem;
      margin-bottom: 1rem;
    }

    h1 {
      margin: 0;
      font-size: clamp(2rem, 6vw, 4.4rem);
      line-height: 1;
      letter-spacing: -.06em;
    }

    .subtitle {
      margin: 1rem auto 0;
      max-width: 720px;
      color: var(--muted);
      font-size: clamp(1rem, 2vw, 1.25rem);
      line-height: 1.6;
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 1rem;
    }

    .card {
      min-height: 230px;
      padding: 1.4rem;
      border: 1px solid var(--card-border);
      border-radius: 26px;
      background: var(--card);
      box-shadow: var(--shadow);
      backdrop-filter: blur(18px);
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      transition: transform .18s ease, border-color .18s ease, background .18s ease;
    }

    .card:hover {
      transform: translateY(-4px);
      border-color: rgba(255,255,255,.35);
      background: rgba(255,255,255,.12);
    }

    .icon {
      width: 48px;
      height: 48px;
      display: grid;
      place-items: center;
      border-radius: 16px;
      font-size: 1.8rem;
      background: rgba(255,255,255,.12);
    }

    .card h2 {
      margin: 1rem 0 .4rem;
      font-size: 1.45rem;
    }

    .card p {
      margin: 0;
      color: var(--muted);
      line-height: 1.5;
    }

    .actions {
      margin-top: 1.2rem;
    }

    a.button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 100%;
      padding: .85rem 1rem;
      border-radius: 16px;
      color: #fff;
      text-decoration: none;
      font-weight: 800;
      letter-spacing: .01em;
    }

    .plex {
      background: linear-gradient(135deg, var(--plex), #ffbf3f);
      color: #111;
    }

    .rutorrent {
      background: linear-gradient(135deg, #16a34a, var(--rutorrent));
      color: #052e16;
    }

    .paypal {
      background: linear-gradient(135deg, var(--paypal), #003087);
    }

    .github {
      background: linear-gradient(135deg, var(--github), #475569);
    }

    footer {
      margin-top: 1.4rem;
      text-align: center;
      color: var(--muted);
      font-size: .92rem;
    }

    code {
      color: #e2e8f0;
      background: rgba(255,255,255,.08);
      border: 1px solid rgba(255,255,255,.12);
      border-radius: .45rem;
      padding: .12rem .35rem;
    }

    @media (max-width: 1050px) {
      .grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
    }

    @media (max-width: 800px) {
      body {
        padding: 1rem;
      }

      .grid {
        grid-template-columns: 1fr;
      }

      .card {
        min-height: 190px;
      }
    }
  </style>
</head>
<body>
  <main>
    <section class="hero">
      <div class="badge">🚀 Freebox Delta VM Debian Media Server</div>
      <h1>Freebox Delta</h1>
      <p class="subtitle">
        Accès rapide aux services multimédias installés sur la VM Debian :
        Plex, ruTorrent et support du projet.
      </p>
    </section>

    <section class="grid">
      <article class="card">
        <div>
          <div class="icon">▶</div>
          <h2>Plex</h2>
          <p>Bibliothèque multimédia et streaming local depuis le serveur Plex de la VM.</p>
        </div>
        <div class="actions">
          <a id="plexLink" class="button plex" href="http://localhost:32400/web">Ouvrir Plex</a>
        </div>
      </article>

      <article class="card">
        <div>
          <div class="icon">⬇</div>
          <h2>ruTorrent</h2>
          <p>Interface web rTorrent protégée par authentification Apache.</p>
        </div>
        <div class="actions">
          <a class="button rutorrent" href="/rutorrent">Ouvrir ruTorrent</a>
        </div>
      </article>

      <article class="card">
        <div>
          <div class="icon">⌘</div>
          <h2>GitHub</h2>
          <p>Code source, README et dernières versions du script Freebox Delta.</p>
        </div>
        <div class="actions">
          <a class="button github" href="https://github.com/PFranck06/Freebox_Delta_VM_Plex_Rutorent" target="_blank" rel="noopener noreferrer">
            Ouvrir le GitHub
          </a>
        </div>
      </article>

      <article class="card">
        <div>
          <div class="icon">❤</div>
          <h2>Donation</h2>
          <p>Soutenir le développement et les scripts Freebox Delta.</p>
        </div>
        <div class="actions">
          <a class="button paypal" href="https://www.paypal.com/paypalme/FPLESSY565" target="_blank" rel="noopener noreferrer">
            PayPal @FPLESSY565
          </a>
        </div>
      </article>
    </section>

    <footer>
      Hôte détecté : <code id="hostName">...</code>
    </footer>
  </main>

  <script>
    const host = window.location.hostname || "localhost";
    document.getElementById("hostName").textContent = host;
    document.getElementById("plexLink").href = "http://" + host + ":32400/web";
  </script>
</body>
</html>
EOF

  chown www-data:www-data /var/www/html/index.html
  chmod 644 /var/www/html/index.html

  cat > /etc/apache2/sites-available/freebox-media.conf <<EOF
<VirtualHost *:80>
    ${SERVERNAME_LINE}
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    Alias /rutorrent ${RUTORRENT_DIR}

    <Directory ${RUTORRENT_DIR}/>
        Options -Indexes -Includes -FollowSymLinks +MultiViews
        AllowOverride None
        AuthType Basic
        AuthName "ruTorrent"
        AuthUserFile ${RUTORRENT_DIR}/.htpasswd
        Require valid-user
    </Directory>

    <Location "/RPC2">
        Require local
    </Location>

    ProxyPass /RPC2 scgi://${RTORRENT_SCGI_HOST}:${RTORRENT_SCGI_PORT}
    ProxyPassReverse /RPC2 scgi://${RTORRENT_SCGI_HOST}:${RTORRENT_SCGI_PORT}

    ErrorLog \${APACHE_LOG_DIR}/freebox-media-error.log
    CustomLog \${APACHE_LOG_DIR}/freebox-media-access.log combined
</VirtualHost>
EOF

  a2dissite 000-default >/dev/null 2>&1 || true
  a2ensite freebox-media >/dev/null
  apache2ctl configtest
  systemctl restart apache2

  if apache2ctl -M 2>/dev/null | grep -Eq 'auth_basic|authn_file'; then
    ok "Modules Apache d'authentification chargés."
  else
    warn "Modules Apache auth_basic/authn_file non confirmés. Vérifie apache2ctl -M."
  fi
fi

if [[ "$DO_SSL" == "yes" ]]; then
  log "Configuration SSL Let's Encrypt pour ${DOMAIN_NAME}"

  if wait_for_port 127.0.0.1 80 20; then
    if certbot --apache -d "${DOMAIN_NAME}" \
      --non-interactive \
      --agree-tos \
      -m "${LETSENCRYPT_EMAIL}" \
      --redirect; then
      ok "Certificat SSL installé."
      systemctl reload apache2
    else
      warn "Certbot a échoué. Vérifie DNS + redirection port 80 vers la VM."
    fi
  else
    warn "Apache HTTP ne répond pas localement sur le port 80, SSL ignoré."
  fi
fi

# -----------------------------
# 4) Plex claim / check
# -----------------------------
if [[ "$DO_PLEX_CLAIM" == "yes" ]]; then
  log "Validation Apache/Plex avant Plex Claim"

  if wait_for_port 127.0.0.1 80 20; then
    ok "Apache est accessible localement."
  else
    warn "Apache n'est pas accessible localement sur 127.0.0.1:80."
  fi

  if systemctl list-unit-files 2>/dev/null | grep -q '^plexmediaserver\.service'; then
    systemctl restart plexmediaserver
  fi

  PLEX_IS_CLAIMED="no"
  PLEX_IDENTITY="/tmp/plex-identity.xml"
  PLEX_PREFS="/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml"

  if wait_for_port 127.0.0.1 32400 60; then
    ok "Plex répond localement sur 127.0.0.1:32400."

    if curl -sS "http://127.0.0.1:32400/identity" -o "${PLEX_IDENTITY}" 2>/dev/null \
      && grep -q 'claimed="1"' "${PLEX_IDENTITY}"; then
      PLEX_IS_CLAIMED="yes"
    fi

    if [[ "${PLEX_IS_CLAIMED}" != "yes" && -f "${PLEX_PREFS}" ]] \
      && grep -Eq 'PlexOnlineToken="[^"]+"' "${PLEX_PREFS}"; then
      PLEX_IS_CLAIMED="yes"
    fi
  else
    warn "Plex ne répond pas sur 127.0.0.1:32400. Le claim risque d'échouer."
  fi

  if [[ "${PLEX_IS_CLAIMED}" == "yes" ]]; then
    PLEX_CLAIM_STATUS="déjà revendiqué"
    ok "Plex est déjà claim/revendiqué : aucune question Plex Claim posée."
  else
    echo
    warn "Plex non claim automatiquement. Méthode fiable :"
    echo "  1) Ouvre maintenant : https://plex.tv/claim"
    echo "  2) Copie le token fraîchement généré."
    echo "  3) Colle-le ci-dessous immédiatement."
    echo "  4) En cas d'échec, la commande manuelle équivalente sera affichée."
    echo
    warn "Le token Plex Claim expire rapidement."
    PLEX_CLAIM_TOKEN="$(prompt "Token Plex Claim fraîchement généré, vide = ignorer" "")"

    PLEX_CLAIM_TOKEN="$(echo "${PLEX_CLAIM_TOKEN}" | tr -d '[:space:]')"
    if [[ "${PLEX_CLAIM_TOKEN}" == *"token="* ]]; then
      PLEX_CLAIM_TOKEN="${PLEX_CLAIM_TOKEN##*token=}"
      PLEX_CLAIM_TOKEN="${PLEX_CLAIM_TOKEN%%&*}"
    fi

    if [[ -n "${PLEX_CLAIM_TOKEN}" ]]; then
      log "Tentative de claim Plex par curl local immédiat"
      CLAIM_RESULT="/tmp/plex-claim-result.xml"
      CLAIM_HTTP="/tmp/plex-claim-http-code.txt"
      rm -f "${CLAIM_RESULT}" "${CLAIM_HTTP}"

      CLAIM_URL_127="http://127.0.0.1:32400/myplex/claim?token=${PLEX_CLAIM_TOKEN}"
      HTTP_CODE="$(curl -sS -o "${CLAIM_RESULT}" -w "%{http_code}" \
        -X POST \
        -H "X-Plex-Product: FreeboxDeltaInstaller" \
        -H "X-Plex-Version: 1.0" \
        -H "X-Plex-Client-Identifier: freebox-delta-vm" \
        "${CLAIM_URL_127}" || echo "000")"
      echo "${HTTP_CODE}" > "${CLAIM_HTTP}"

      if [[ "${HTTP_CODE}" == "200" ]] && grep -Eqi 'authToken|claimed|MyPlex' "${CLAIM_RESULT}"; then
        PLEX_CLAIM_STATUS="revendiqué maintenant"
        ok "Plex semble revendiqué correctement via 127.0.0.1."
      else
        warn "Premier claim via 127.0.0.1 non confirmé. Code HTTP: ${HTTP_CODE}"
        warn "Tentative fallback via localhost."

        CLAIM_URL_LOCALHOST="http://localhost:32400/myplex/claim?token=${PLEX_CLAIM_TOKEN}"
        HTTP_CODE="$(curl -sS -o "${CLAIM_RESULT}" -w "%{http_code}" \
          -X POST \
          -H "X-Plex-Product: FreeboxDeltaInstaller" \
          -H "X-Plex-Version: 1.0" \
          -H "X-Plex-Client-Identifier: freebox-delta-vm" \
          "${CLAIM_URL_LOCALHOST}" || echo "000")"
        echo "${HTTP_CODE}" > "${CLAIM_HTTP}"

        if [[ "${HTTP_CODE}" == "200" ]] && grep -Eqi 'authToken|claimed|MyPlex' "${CLAIM_RESULT}"; then
          PLEX_CLAIM_STATUS="revendiqué maintenant"
          ok "Plex semble revendiqué correctement via localhost."
        else
          PLEX_CLAIM_STATUS="échec ou non confirmé"
          warn "Échec ou réponse non confirmée du claim Plex. Code HTTP: ${HTTP_CODE}"
          warn "Réponse sauvegardée dans ${CLAIM_RESULT}"
          warn "Commande manuelle équivalente à retenter immédiatement avec un nouveau token :"
          echo "curl -X POST 'http://127.0.0.1:32400/myplex/claim?token=TON_TOKEN'"
          echo
          warn "Aperçu réponse Plex :"
          sed -n '1,8p' "${CLAIM_RESULT}" 2>/dev/null || true
        fi
      fi
    else
      PLEX_CLAIM_STATUS="ignoré"
      warn "Aucun Plex Claim Token fourni. Le serveur Plex devra être revendiqué manuellement."
    fi
  fi
else
  # Lightweight status check for summary.
  PLEX_PREFS="/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml"
  if [[ -f "${PLEX_PREFS}" ]] && grep -Eq 'PlexOnlineToken="[^"]+"' "${PLEX_PREFS}"; then
    PLEX_CLAIM_STATUS="déjà revendiqué"
  else
    PLEX_CLAIM_STATUS="non vérifié"
COMMAND="${1:-auto}"
  fi
fi

save_state

# -----------------------------
# 5) Final summary - keep this as the last section of the script
# -----------------------------
echo
echo -e "${BOLD}${CYAN}Résumé final${RESET}"
echo "------------------------------------------------------------"
echo "Mode                             : ${INSTALL_MODE}"
echo "Utilisateur système              : ${MAIN_USER}"
echo "SSH                              : port ${SSH_PORT}"
echo "Apache                           : $(service_status_short apache2.service)"
echo "rTorrent                         : $(service_status_short rtorrent.service)"
echo "Plex Media Server                : $(service_status_short plexmediaserver.service)"
echo "Plex Claim                       : ${PLEX_CLAIM_STATUS}"
echo "Accueil Apache                   : http://<IP_VM>/"
echo "GitHub script                    : https://github.com/PFranck06/Freebox_Delta_VM_Plex_Rutorent"
echo "ruTorrent                        : http://<IP_VM>/rutorrent"
if [[ -n "${DOMAIN_NAME}" ]]; then
  echo "ruTorrent domaine                : https://${DOMAIN_NAME}/rutorrent"
fi
echo "Utilisateur HTTP ruTorrent       : ${RUTORRENT_HTTP_USER}"
echo "Mot de passe HTTP ruTorrent      : ${RUTORRENT_HTTP_PASS}"
echo "Identifiants sauvegardés         : ${CREDENTIALS_FILE}"
echo "Plex                             : http://<IP_VM>:32400/web"
echo "Disque principal rTorrent        : ${MEDIA_ROOT}"
echo "Tous les disques Freebox         : ${FREEBOX_MOUNTS_DISPLAY}"
echo "Explorateur ruTorrent top dir    : /mnt/"
echo "Dossier torrents                 : ${TOR_BASE}"
echo "Watch dir                        : ${WATCH_DIR}"
echo "Downloads                        : ${DOWNLOAD_DIR}"
echo "Session                          : ${SESSION_DIR}"
echo "Plugins ruTorrent sur disque     : ${PLUGIN_COUNT}"
echo "Fichier état install/update      : ${STATE_FILE}"
echo "Log installation                 : ${LOG_FILE}"
echo "Log ruTorrent                    : /tmp/rutorrent-errors.log"
echo "------------------------------------------------------------"

echo
echo -e "${CYAN}Ports en écoute utiles :${RESET}"
ss -ltnup 2>/dev/null | grep -E "(:${SSH_PORT}|:80|:443|:32400|:${RTORRENT_PEER_PORT}|:${RTORRENT_SCGI_PORT})" || true

echo
echo -e "${CYAN}Règles UFW :${RESET}"
ufw status numbered || true

echo
ok "Installation / update terminé."
